replicaCount: 2

image:
  repository: alexeyeliseev/simplerest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000
  targetPort: 8000

postgresql:
  enabled: true
  fullname: postgres-dicts-common
  name: postgres-dicts-common
  fullnameOverride: postgresql-dicts-common
  host: my-postgresql
  postgresqlUsername: alexey
  postgresqlPassword: a
  postgresqlDatabase: myapp
  service:
    port: "5432"
    type: NodePort
  postgresqlPostgresPassword: pp
  metrics:
    enabled: true
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      loadBalancerIP:
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s

ingress:
  enabled: true
  annotations:
    { nginx.ingress.kubernetes.io/rewrite-target: /$2 }
  hosts:
    - host: arch.homework
      path: /otusapp($|/)(.*)

metrics:
  serviceMonitor:
    enabled: true
