{{- $fullname := include "hello-chart.fullname" . -}}
{{- $selectorLabels := include "hello-chart.selectorLabels" . -}}
{{- $port := .Values.service.port -}}
{{- $targetPort := .Values.service.targetPort -}}
{{- $type := .Values.service.type -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullname }}-service"
spec:
  selector:
  {{ $selectorLabels | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $targetPort }}
  type: {{ $type }}
