{{- $fullname := include "hello-chart.fullname" . -}}
{{- $selectorLabels := include "hello-chart.selectorLabels" . -}}
{{- $port := .Values.service.port -}}
{{- $targetPort := .Values.service.targetPort -}}
{{- $type := .Values.service.type -}}
{{- $labels := include "hello-chart.labels" . -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullname }}-service"
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $targetPort }}
      name: web
  selector:
  {{ $selectorLabels | nindent 4 }}
