#TODO setup port from ENV
server.port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  metrics:
    export.prometheus.enabled: true
    distribution.percentiles-histogram:
      - controller.health.version.requests: true
      - controller.user.requests: true
    enable:
      - controller.health.version.requests: true
      - controller.user.requests: true
