apiVersion: batch/v1
kind: Job
metadata:
  name: stresstest
spec:
  template:
    metadata:
      name: stresstest
    spec:
      containers:
        - name: stresstest-get
          image: jordi/ab
          env:
            - name: INGRESS_CONTROLLER_NAME
              value: nginx-nginx-ingress-controller
            - name: REQUEST_NUMBER
              value: "3"
          command:
            - sh
            - "-c"
            - |
              /bin/sh <<'EOF'

              # CREATE
              while true; \
                do echo "{\"name\":\"test$RANDOM\"}" > user.json;
                ab -n$REQUEST_NUMBER -H 'Host: arch.homework' -T application/json -p ./user.json http://$INGRESS_CONTROLLER_NAME/otusapp/users; \
                sleep 1; \
              done &

              # GET
              while true; \
                do ab -n$REQUEST_NUMBER -H 'Host: arch.homework' http://$INGRESS_CONTROLLER_NAME/otusapp/users/1; \
                sleep 1; \
              done &

              # UPDATE
              while true; \
                do echo "{\"name\":\"test$RANDOM\"}" > user.json;
                ab -n$REQUEST_NUMBER -H 'Host: arch.homework' -T application/json -u ./user.json http://$INGRESS_CONTROLLER_NAME/otusapp/users/1; \
                sleep 1; \
              done &

              # DELETE
              while true; \
                do ab -n$REQUEST_NUMBER -H 'Host: arch.homework' -m DELETE http://$INGRESS_CONTROLLER_NAME/otusapp/users/100; \
                sleep 1; \
              done &

              # GET ALL
              while true; \
                do ab -n$REQUEST_NUMBER -H 'Host: arch.homework' http://$INGRESS_CONTROLLER_NAME/otusapp/users; \
                sleep 1; \
              done;

              EOF
      restartPolicy: Never
