apiVersion: v1
kind: ConfigMap
metadata:
 name: hello-config
data:
 TEST_APP: testApp
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9teWFwcA==
  DB_NAME: bXlhcHA=
  DB_USER: YWxleGV5
  DB_PASSWORD: YQ==
  DB_PSQL_URL: cG9zdGdyZXNxbDovL2FsZXhleTphQHBvc3RncmVzL215YXBw
